Fix error when getting tapper text (#1034)
* Fix error when getting tapper text

There's a weird error that seems to happen because a new error in Chromium? 

```
ProtocolError: Protocol error (DOM.resolveNode): Node with given id does not belong to the document
           at <instance_members_initializer> (/opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/@suffolklitlab/alkiln/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:93:14)
           at new Callback (/opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/@suffolklitlab/alkiln/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:97:16)
           at CallbackRegistry.create (/opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/@suffolklitlab/alkiln/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)
           at Connection._rawSend (/opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/@suffolklitlab/alkiln/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:89:26)
           at CdpCDPSession.send (/opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/@suffolklitlab/alkiln/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:66:33)
           at IsolatedWorld.adoptBackendNode (/opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/@suffolklitlab/alkiln/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:109:46)
           at IsolatedWorld.adoptHandle (/opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/@suffolklitlab/alkiln/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:126:28)
           at async CdpElementHandle.<anonymous> (/opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/@suffolklitlab/alkiln/node_modules/puppeteer-core/lib/cjs/puppeteer/api/ElementHandle.js:264:60)
           at async Object.tapElementAndStayOnPage (/opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/@suffolklitlab/alkiln/lib/scope.js:298:29)
           at async Object.tapElementAndNavigate (/opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/@suffolklitlab/alkiln/lib/scope.js:263:5)
```

More context of the error: https://github.com/SuffolkLITLab/docassemble-ALWeaver/actions/runs/19590236387?pr=953

Some external discussion of it: https://github.com/SeleniumHQ/selenium/issues/15401

This is a little of a hacky fix, but simply not trying to get the text content
before clicking the object is fixes the issue.

* Trying different debug things

* Fix `.map()` function to return Promises

* Fix typo

* Use npm published version, update CHANGELOG

* Remove extraneous line

---------

Co-authored-by: plocket <52798256+plocket@users.noreply.github.com>
Co-authored-by: will-morningstar <mxwillmorningstar@gmail.com>